version: '3'
services:
  masterDB:
    env_file:
      - mysql-server.env
    image: mysql/mysql-server:8.0.12
    platform: linux/amd64
    volumes:
      - master-data:/var/lib/mysql
    ports:
      - "3301:3306"
    command: [ "mysqld", "--server_id=1","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password" ]

  slaveDB:
      env_file:
        - mysql-server.env
      image: mysql/mysql-server:8.0.12
      platform: linux/amd64
      volumes:
        - slave-data:/var/lib/mysql
      command: [ "mysqld","--server_id=2","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password" ]
      ports:
        - "3302:3306"

  slaveDB2:
      env_file:
        - mysql-server.env
      image: mysql/mysql-server:8.0.12
      platform: linux/amd64
      volumes:
        - slave2-data:/var/lib/mysql
      command: [ "mysqld","--server_id=3","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password" ]
      ports:
        - "3303:3306"

  mysql-shell:
      env_file:
        - mysql-shell.env
      image: neumayer/mysql-shell-batch
      platform: linux/amd64
      volumes:
        - ./scripts/:/scripts/
      depends_on:
        - masterDB
        - slaveDB
        - slaveDB2

  mysql-router:
      env_file:
        - mysql-router.env
      image: mysql/mysql-router:8.0
      platform: linux/amd64
      ports:
        - "6446:6446"
      depends_on:
        - masterDB
        - slaveDB
        - slaveDB2
        - mysql-shell
      restart: on-failure

  migrate:
    image: migrate/migrate
    restart: on-failure
    depends_on:
      - masterDB
    volumes:
      - ./server/zarf/migrations:/migrations
    command: ["-path", "./migrations", "-database", "${MHOST}", "up"]

  server:
    container_name: server
    restart: on-failure
    build: ./server/
    ports:
      - "${HOST_SERVER_PORT}:5000"
    env_file:
      - service.env
    depends_on:
      - mysql-router

  web:
    build: ./client/
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      REACT_APP_BASE_API_URL: http://localhost:${HOST_SERVER_PORT}/api

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  master-data:
  slave-data:
  slave2-data:
