version: '3'
services:
  database:
    image: "mysql"
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: social
    ports:
      - "3306:3306"
    volumes:
      - database-data:/var/lib/mysql

  server:
    container_name: server
    restart: on-failure
    build: ..
    ports:
      - "5000:5000"
    environment:
      HIGHLOAD_DB_HOST: mysql
    depends_on:
      - database

  web:
    build: ../client/
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      REACT_APP_BASE_API_URL: http://host.docker.internal:5000/api

volumes:
  database-data:
